name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create rpglooter com.poulstudio.rpglooter RPGlooter
        cp -r www/* rpglooter/www/
        cp config.xml rpglooter/
        cd rpglooter
        cordova platform add android

    - name: Build APK
      run: |
        cd rpglooter
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
